title: New Awesomeness Blog
author: Alex
email: alexander.sloof@okstate.edu
description: > # this means to ignore newlines until "baseurl:"
  This blog page is for learning use of GitHub and data analytics using R & Python.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

